name: "Check linting"

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        command: ["lint:eslint", "lint:prettier", "test"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm_store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm_store-

      - uses: pnpm/action-setup@v2
        with:
          version: 6.32
          run_install: true

      - run: cp .env.ci .env.local

      - run: pnpm ${{ matrix.command }}
